# Your main hugo.toml file

baseURL = "/"
languageCode = "en-us"
title = "Mind Refactor"
theme = "ananke"

[taxonomies]
  category = "categories"
  tag = "tags"

[module.hugoVersion]
  min = "0.128.0"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Articles"
  url = "/posts/"
  weight = 2

[params]
  description = "Mind Refactor is a blog about software development, programming, and technology."

  # ADD THIS LINE with the path to your image
  featured_image = "/images/header-background.jpg"
  
  [params.ananke]
    main_css = "ananke/css/main.css"

  [[params.ananke_socials]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/your-real-profile-url"